server:
  port: 8081
  servlet:
    context-path: /luckymoney

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/luckymoney?characterEncoding=utf-8
    username: root
    password: kinly1993
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
